fixtures:
  repositories:
    monitoring_check:
      repo: 'git@sysgit.yelpcorp.com:mirrors/Yelp/puppet-monitoring_check.git'
      ref:  '8b3d5d4e0bb43d072339a58e305b39ebd319c7a6'
    stdlib:
      repo: 'git@sysgit.yelpcorp.com:mirrors/puppetlabs/puppetlabs-stdlib.git'
      ref:  '4.3.2'
  symlinks:
    cron: "#{source_dir}"
