#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail

# Puppet puts marker files in place with the current mtime.  Our first task is
# to set them forward in time so that we can easily distinguish cronjobs that
# haven't yet completed successfully.  We put them forward to Y2K38
success_file="/nail/run/success_wrapper/${1}"
[ -e "${success_file}" ] && touch -d '@2147483647' "/nail/run/success_wrapper/${1}"
initctl emit --no-wait "${1}"
